[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[env]
# Environment variables for ARM64 cross-compilation
CC_aarch64_unknown_linux_gnu = "aarch64-linux-gnu-gcc"
CXX_aarch64_unknown_linux_gnu = "aarch64-linux-gnu-g++"
AR_aarch64_unknown_linux_gnu = "aarch64-linux-gnu-ar"
CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER = "aarch64-linux-gnu-gcc"

# Fix for ring compilation on ARM64
CFLAGS_aarch64_unknown_linux_gnu = "-D__ARM_ARCH=8 -march=armv8-a"
CXXFLAGS_aarch64_unknown_linux_gnu = "-D__ARM_ARCH=8 -march=armv8-a"